services:
  db:
    image: postgres:16
    container_name: foxi-dating-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: foxi
    ports:
      - "5433:5432"
    volumes:
      - foxi-dating-data:/var/lib/postgresql/data
      - ./sql-innit.sql:/docker-entrypoint-initdb.d/sql-innit.sql # Ensure filename matches!
    restart: unless-stopped

volumes:
  foxi-dating-data: